version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_sirclo-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - .docker/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  web-server:
    image: nginx:alpine
    container_name: test_sirclo-web_server
    restart: unless-stopped
    tty: true
    ports:
      - "82:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: test_sirclo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - "33061:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
